name: CICD

on:
  push:
    branches: [cicd-docker-ec2]  # Ensure this matches the branch you're working on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t tagore555/node-app:latest .

      - name: Publish image to Docker Hub
        run: docker push tagore555/node-app:latest
